### ISSUE TITLE
KeyError: 'belongs to'

### ISSUE THREAD

**Issue by eccentricpzy** [siqichen-usc/YYS-optimization#2]
Traceback (most recent call last):
  File "D:\Anaconda\lib\site-packages\pandas\indexes\base.py", line 1945, in get_loc
    return self._engine.get_loc(key)
  File "pandas\index.pyx", line 137, in pandas.index.IndexEngine.get_loc (pandas\index.c:4154)
  File "pandas\index.pyx", line 159, in pandas.index.IndexEngine.get_loc (pandas\index.c:4018)
  File "pandas\hashtable.pyx", line 675, in pandas.hashtable.PyObjectHashTable.get_item (pandas\hashtable.c:12368)
  File "pandas\hashtable.pyx", line 683, in pandas.hashtable.PyObjectHashTable.get_item (pandas\hashtable.c:12322)
KeyError: 'belongs to'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/panzhiyuan/Desktop/YYS-optimization-master/YYS.py", line 275, in <module>
    optimize(inputFile)
  File "C:/Users/panzhiyuan/Desktop/YYS-optimization-master/YYS.py", line 27, in optimize
    level = level[level['belongs to'] == 1]
  File "D:\Anaconda\lib\site-packages\pandas\core\frame.py", line 1997, in __getitem__
    return self._getitem_column(key)
  File "D:\Anaconda\lib\site-packages\pandas\core\frame.py", line 2004, in _getitem_column
    return self._get_item_cache(key)
  File "D:\Anaconda\lib\site-packages\pandas\core\generic.py", line 1350, in _get_item_cache
    values = self._data.get(item)
  File "D:\Anaconda\lib\site-packages\pandas\core\internals.py", line 3290, in get
    loc = self.items.get_loc(item)
  File "D:\Anaconda\lib\site-packages\pandas\indexes\base.py", line 1947, in get_loc
    return self._engine.get_loc(self._maybe_cast_indexer(key))
  File "pandas\index.pyx", line 137, in pandas.index.IndexEngine.get_loc (pandas\index.c:4154)
  File "pandas\index.pyx", line 159, in pandas.index.IndexEngine.get_loc (pandas\index.c:4018)
  File "pandas\hashtable.pyx", line 675, in pandas.hashtable.PyObjectHashTable.get_item (pandas\hashtable.c:12368)
  File "pandas\hashtable.pyx", line 683, in pandas.hashtable.PyObjectHashTable.get_item (pandas\hashtable.c:12322)
KeyError: 'belongs to'

**Comment by siqichen-usc** [comment]
应该是input.xlsx的input工作表的单元格被移动了，所以后面的一些基于表格的运算错了，建议重新下载input.xlsx，并输入数据或者粘贴值。
